# Generated by Django 4.0.3 on 2022-04-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='github_account',
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='github_account', to='users.candidate'),
            preserve_default=False,
        ),
    ]
