# Generated by Django 4.0.4 on 2022-05-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_candidate_current_employer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-work_score']},
        ),
    ]
