# Generated by Django 4.0.3 on 2022-04-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_candidate_github_account_githubaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to='users.candidate'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.githubaccount'),
        ),
    ]
