# Generated by Django 4.0.3 on 2022-04-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_githubaccount_owner_alter_githubrepo_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='repo_count',
            new_name='repos_count',
        ),
        migrations.DeleteModel(
            name='GithubRepo',
        ),
    ]
