# Generated by Django 4.0.4 on 2022-05-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preprofile_candidate_pre_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreProfile',
            new_name='CandidatePreProfile',
        ),
    ]
