# Generated by Django 4.0.3 on 2022-04-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_url_githubaccount_profile_html_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubContributor',
        ),
    ]
