# Generated by Django 4.0.4 on 2022-05-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_preprofile_candidatepreprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatepreprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='pre_profile',
        ),
    ]
