# Generated by Django 4.0.4 on 2022-05-10 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_candidatepreprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('website_url', models.CharField(max_length=255, null=True)),
                ('github_url', models.CharField(max_length=255, null=True)),
                ('linkedin_url', models.CharField(max_length=255, null=True)),
                ('employer', models.CharField(max_length=255, null=True)),
                ('verified_job_looker', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CandidatePreProfile',
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='users.candidateprofile'),
        ),
    ]
