# Generated by Django 4.0.4 on 2022-05-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_candidatepreprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pre_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='users.candidatepreprofile'),
        ),
    ]
