# Generated by Django 4.0.3 on 2022-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_githubaccount_programming_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='programming_languages_json',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='programming_languages',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
