# Generated by Django 4.0.3 on 2022-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_githubaccount_programming_languages_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='technologies_json',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
