# Generated by Django 4.0.4 on 2022-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_candidate_pre_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='TODO', max_length=255),
            preserve_default=False,
        ),
    ]
