# Generated by Django 4.0.3 on 2022-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_githubaccount_technologies_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='programming_languages_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='technologies_json',
            field=models.JSONField(null=True),
        ),
    ]
