# Generated by Django 4.0.3 on 2022-04-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_githubaccount_programming_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='programming_languages_json',
            new_name='programming_languages',
        ),
        migrations.RenameField(
            model_name='githubaccount',
            old_name='technologies_json',
            new_name='technologies',
        ),
    ]
