# Generated by Django 4.0.3 on 2022-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_programming_languages_json_githubaccount_programming_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_employer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hireability_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='popularity_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
