# Generated by Django 4.0.4 on 2022-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companydomainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
