# Generated by Django 4.0.3 on 2022-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_candidate_current_employer_candidate_current_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='githubaccount',
            old_name='technologies',
            new_name='topics',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='twitter_username',
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='contributions_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='following_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
