# Generated by Django 4.0.4 on 2022-06-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employee_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='fit_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hireability_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='popularity_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_score',
            field=models.FloatField(null=True),
        ),
    ]
