# Generated by Django 4.0.3 on 2022-04-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_followers_githubaccount_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='topics',
            new_name='technologies_and_topics',
        ),
    ]
