# Generated by Django 4.0.3 on 2022-04-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_topics_githubaccount_technologies_and_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='programming_languages',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='technologies_and_topics',
        ),
    ]
