# Generated by Django 4.0.3 on 2022-04-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_githubaccount_programming_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='follower_following_difference',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
