# Generated by Django 4.0.3 on 2022-04-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_githubaccount_follower_following_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='following_count',
        ),
    ]
