# Generated by Django 4.0.3 on 2022-04-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_githubaccount_following_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='follower_following_difference',
            new_name='followers_following_counts_difference',
        ),
    ]
