# Generated by Django 4.0.3 on 2022-04-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_follower_following_difference_githubaccount_followers_following_counts_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_accounts', to='users.candidate'),
        ),
    ]
