# Generated by Django 4.0.3 on 2022-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_githubaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fit_score',
            field=models.FloatField(null=True),
        ),
    ]
