# Generated by Django 4.0.3 on 2022-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_candidate_fit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='fit_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hireability_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='popularity_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
