# Generated by Django 4.0.3 on 2022-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_candidate_fit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_contributions_count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_followers_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_followers_following_counts_difference',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_gists_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_repos_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
