# Generated by Django 4.0.4 on 2022-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companydomainname'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='opened_by',
            field=models.ManyToManyField(to='users.employee'),
        ),
    ]
