# Generated by Django 4.0.3 on 2022-04-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_rename_repo_count_githubaccount_repos_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('stargazers_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('main_language', models.CharField(max_length=255, null=True)),
                ('topics', models.TextField(null=True)),
                ('repo_url', models.CharField(max_length=255)),
                ('collaborators_url', models.CharField(max_length=255)),
                ('languages_url', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.githubaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
