# Generated by Django 4.0.3 on 2022-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='repo_url',
            new_name='repo_html_url',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='collaborators_url',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='languages_url',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='owner',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='repo_api_url',
            field=models.CharField(default='tmp', max_length=255),
            preserve_default=False,
        ),
    ]
