# Generated by Django 4.0.3 on 2022-04-17 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_githubcontributor'),
        ('repos', '0002_rename_repo_url_githubrepo_repo_html_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.githubaccount')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.githubrepo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
