# Generated by Django 4.0.3 on 2022-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_programminglanguage_githubrepolanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='topics',
        ),
        migrations.DeleteModel(
            name='GithubRepoLanguage',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='topics',
            field=models.ManyToManyField(to='repos.githubtopic'),
        ),
    ]
