# Generated by Django 4.0.3 on 2022-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_githubtopic_remove_githubrepo_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='main_language',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='main_language',
            field=models.ManyToManyField(to='repos.githubprogramminglanguage'),
        ),
    ]
