# Generated by Django 4.0.3 on 2022-04-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0006_githubprogramminglanguage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='topics',
            new_name='technologies_and_topics',
        ),
    ]
