# Generated by Django 4.0.3 on 2022-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_rename_topics_githubrepo_technologies_and_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='size_in_kilobytes',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='watchers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
