# Generated by Django 4.0.3 on 2022-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0009_alter_githubrepocontributor_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='normalized_forks_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='normalized_size_in_kilobytes',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='normalized_stargazers_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='normalized_watchers_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
