# Generated by Django 4.0.4 on 2022-05-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_companydomainname'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Sourcing', 'Sourcing'), ('Screening', 'Screening'), ('Interviewing', 'Interviewing'), ('Selecting', 'Selecting'), ('Closed', 'Closed')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('base_compensation', models.IntegerField()),
                ('equity_compensation', models.IntegerField()),
                ('other_compensation', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('programming_languages', models.ManyToManyField(related_name='openings', to='technologies.programminglanguage')),
                ('technologies', models.ManyToManyField(related_name='openings', to='technologies.technology')),
                ('topics', models.ManyToManyField(related_name='openings', to='technologies.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
