# Generated by Django 4.0.4 on 2022-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='base_compensation',
            new_name='base_compensation_min',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='equity_compensation',
            new_name='equity_compensation_min',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='other_compensation',
            new_name='other_compensation_min',
        ),
        migrations.AddField(
            model_name='opening',
            name='base_compensation_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='equity_compensation_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='other_compensation_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
