# Generated by Django 4.0.4 on 2022-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_alter_opening_base_compensation_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='opening',
            name='years_of_experience_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='years_of_experience_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
