# Generated by Django 4.0.4 on 2022-05-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0005_opening_base_compensation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='base_compensation_min',
            field=models.IntegerField(null=True),
        ),
    ]
