# Generated by Django 4.0.4 on 2022-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0006_alter_opening_base_compensation_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(choices=[('kr', 'South-Korea')], max_length=255)),
                ('city', models.CharField(choices=[('seoul', 'Seoul')], max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
