# Generated by Django 4.0.4 on 2022-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0008_opening_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='base_compensation_currency',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='base_compensation_max',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='base_compensation_min',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='equity_compensation_currency',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='equity_compensation_max',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='equity_compensation_min',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='location',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='other_compensation_currency',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='other_compensation_max',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='other_compensation_min',
        ),
    ]
