# Generated by Django 4.0.4 on 2022-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0009_remove_opening_base_compensation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='years_of_experience_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
