# Generated by Django 4.0.4 on 2022-05-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companydomainname'),
        ('openings', '0012_openingcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_openings', to='users.employee'),
        ),
    ]
