# Generated by Django 4.0.4 on 2022-05-30 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companydomainname'),
        ('openings', '0014_rename_created_by_opening_opening_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='opening_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_openings', to='users.employee'),
        ),
    ]
