# Generated by Django 4.0.4 on 2022-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0016_alter_opening_years_of_experience_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
