# Generated by Django 4.0.4 on 2022-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='programming_languages',
            field=models.ManyToManyField(to='technologies.programminglanguage'),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='technologies_and_topics',
            field=models.ManyToManyField(to='technologies.topic'),
        ),
    ]
