# Generated by Django 4.0.4 on 2022-04-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_githubaccount_programming_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='programming_languages',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='technologies_and_topics',
        ),
    ]
