# Generated by Django 4.0.4 on 2022-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_githubaccounttopic_githubaccounttechnology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccountlanguage',
            name='language_share',
        ),
        migrations.RemoveField(
            model_name='githubaccounttechnology',
            name='technology_share',
        ),
        migrations.RemoveField(
            model_name='githubaccounttopic',
            name='topic_share',
        ),
    ]
