# Generated by Django 4.0.4 on 2022-04-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_remove_githubaccountlanguage_language_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepocontributor',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='github.githubrepo'),
        ),
    ]
