# Generated by Django 4.0.4 on 2022-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_alter_githubrepocontributor_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='normalized_programming_languages_count',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='programming_languages_count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
