# Generated by Django 4.0.4 on 2022-05-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_githubrepo_normalized_programming_languages_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccountlanguage',
            name='language_share',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
