# Generated by Django 4.0.4 on 2022-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0010_githubaccountlanguage_language_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccounttopic',
            name='topics_share',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
