# Generated by Django 4.0.4 on 2022-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0012_rename_topics_share_githubaccounttopic_topic_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepolanguage',
            name='language_contribution',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
