# Generated by Django 4.0.4 on 2022-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0013_githubrepolanguage_language_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccounttechnology',
            name='technology_share',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
