# Generated by Django 4.0.4 on 2022-05-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0015_alter_githubrepocontributor_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='repositories',
            field=models.ManyToManyField(related_name='collaborators', to='github.githubrepo'),
        ),
    ]
