# Generated by Django 4.0.4 on 2022-05-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0016_githubaccount_repositories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='repositories',
            new_name='repos',
        ),
    ]
