# Generated by Django 4.0.4 on 2022-05-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0020_githubaccount_github_account_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='normalized_size_in_kilobytes',
            new_name='normalized_size_in_bytes',
        ),
        migrations.RenameField(
            model_name='githubrepo',
            old_name='size_in_kilobytes',
            new_name='size_in_bytes',
        ),
    ]
