# Generated by Django 4.0.4 on 2022-05-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0021_rename_normalized_size_in_kilobytes_githubrepo_normalized_size_in_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccountlanguage',
            name='language_share_current_year',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccountlanguage',
            name='language_share_second_year',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccountlanguage',
            name='language_share_third_year',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
    ]
