# Generated by Django 4.0.4 on 2022-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0023_githuborganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='organizations',
            field=models.ManyToManyField(related_name='members', to='github.githuborganization'),
        ),
    ]
