# Generated by Django 4.0.4 on 2022-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0028_alter_githubcontributionscalendar_daily_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='contributions_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='organizations_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='repos_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
