# Generated by Django 4.0.4 on 2022-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0029_githubaccount_contributions_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='languages_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
