# Generated by Django 4.0.4 on 2022-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0030_githubrepo_languages_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='normalized_contributions_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='normalized_followers_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='normalized_followers_following_counts_difference',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='normalized_gists_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccount',
            name='normalized_repos_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccountlanguage',
            name='language_share',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccountlanguage',
            name='language_share_current_year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccountlanguage',
            name='language_share_second_year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccountlanguage',
            name='language_share_third_year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccounttechnology',
            name='technology_share',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubaccounttopic',
            name='topic_share',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='normalized_forks_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='normalized_programming_languages_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='normalized_size_in_bytes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='normalized_stargazers_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='normalized_watchers_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepolanguage',
            name='language_contribution',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepolanguage',
            name='language_share',
            field=models.FloatField(null=True),
        ),
    ]
