# Generated by Django 4.0.4 on 2022-06-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0031_alter_githubaccount_normalized_contributions_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='contributions_count',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='gists_count',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='normalized_contributions_count',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='normalized_gists_count',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='normalized_repos_count',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='repos_count',
        ),
    ]
