# Generated by Django 4.0.4 on 2022-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0032_remove_githubaccount_contributions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='following_count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_following_count',
            field=models.FloatField(null=True),
        ),
    ]
