# Generated by Django 4.0.4 on 2022-06-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0033_githubaccount_following_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='profile_api_url',
        ),
    ]
