# Generated by Django 4.0.4 on 2022-06-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0034_remove_githubaccount_profile_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_contributions_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_repos_count',
            field=models.FloatField(null=True),
        ),
    ]
