# Generated by Django 4.0.4 on 2022-06-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0035_githubaccount_normalized_contributions_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccount',
            name='followers_following_counts_difference',
        ),
        migrations.RemoveField(
            model_name='githubaccount',
            name='normalized_followers_following_counts_difference',
        ),
    ]
