# Generated by Django 4.0.4 on 2022-06-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0036_remove_githubaccount_followers_following_counts_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_average_codebase_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_average_fork_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_average_language_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_average_stargazer_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_average_watcher_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_codebase_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_followers_following_counts_difference',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_fork_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_language_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_stargazer_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_topic_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='normalized_watcher_count',
            field=models.FloatField(null=True),
        ),
    ]
