# Generated by Django 4.0.4 on 2022-06-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0037_githubaccount_normalized_average_codebase_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='normalized_followers_following_counts_difference',
            new_name='normalized_follower_following_count_difference',
        ),
    ]
