# Generated by Django 4.0.4 on 2022-06-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0039_remove_githubrepo_normalized_forks_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubaccount',
            old_name='contributions_updated_at',
            new_name='contributions_scraped_at',
        ),
        migrations.RenameField(
            model_name='githubaccount',
            old_name='organizations_updated_at',
            new_name='organizations_scraped_at',
        ),
        migrations.RenameField(
            model_name='githubaccount',
            old_name='repos_updated_at',
            new_name='repos_scraped_at',
        ),
    ]
