# Generated by Django 4.0.4 on 2022-06-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0040_rename_contributions_updated_at_githubaccount_contributions_scraped_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='languages_updated_at',
            new_name='languages_scraped_at',
        ),
    ]
