# Generated by Django 4.0.4 on 2022-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0041_rename_languages_updated_at_githubrepo_languages_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='account_scraped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
