# Generated by Django 4.0.4 on 2022-06-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0043_rename_github_account_created_at_githubaccount_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='owner_username',
            field=models.CharField(default='TODO', max_length=255),
            preserve_default=False,
        ),
    ]
