# Generated by Django 4.0.4 on 2022-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0044_githubrepo_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='repo_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='repo_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
