# Generated by Django 4.0.4 on 2022-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
