name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env File
        run: |
          touch .env
          echo PRODUCTION=TRUE >> .env
          echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} >> .env
          echo GOOGLE_CLOUD_REGION=${{ secrets.GOOGLE_CLOUD_REGION }} >> .env
          echo USE_CLOUD_SQL_AUTH_PROXY=TRUE >> .env
          echo GOOGLE_CLOUDSQL_INSTANCE_NAME=${{ secrets.GOOGLE_CLOUDSQL_INSTANCE_NAME }} >> .env
          echo DATABASE_PRODUCTION_NAME=${{ secrets.DATABASE_PRODUCTION_NAME }} >> .env
          echo DATABASE_PRODUCTION_USER=${{ secrets.DATABASE_PRODUCTION_USER }} >> .env
          echo DATABASE_PRODUCTION_PASSWORD=${{ secrets.DATABASE_PRODUCTION_PASSWORD }} >> .env
          echo DATABASE_PRODUCTION_USER=${{ secrets.DATABASE_PRODUCTION_USER }} >> .env
          echo DATABASE_PRODUCTION_HOST=/cloudsql/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}:${{ secrets.GOOGLE_CLOUD_REGION }}:${{ secrets.GOOGLE_CLOUDSQL_INSTANCE_NAME }} >> .env
          echo DATABASE_PRODUCTION_PORT= >> .env
          echo GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} >> .env
          cat .env
      - name: Google Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1.0.1
        with:
          creds: ${{ secrets.GOOGLE_CLOUDSQL_SERVICE_ACCOUNT_KEY }}
          instance: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}:${{ secrets.GOOGLE_CLOUD_REGION }}:${{ secrets.GOOGLE_CLOUDSQL_INSTANCE_NAME }}
      - name: Run Tests
        run: |
          python manage.py test
          
